### ISSUE TITLE
Error while connecting to model.json using spark pools on azure

### ISSUE THREAD

**Issue by RithwikChhugani** [Azure/spark-cdm-connector#113]
I am trying to connect to a model.json file located in a data lake folder. 
Below is the code that I am using to connect. 

val df = spark.read.format("com.microsoft.cdm")
                .option("storage","<storageaccountname>.dfs.core.windows.net")
                .option("cdmModel", "https://....../model.json")
                .option("entity", "account")
                .load()

After running the cell with the above code in it, the following is the error. 

<img width="662" alt="Screen Shot 2022-11-30 at 3 32 11 pm" src="https://user-images.githubusercontent.com/44079548/204708106-43c5f7e7-bb76-4ba1-9ba8-cbb231bae3be.png">

Any help would be appreciated.

**Comment by kecheung** [comment]
You should check the documents. Error message says you are missing an argument. 
https://github.com/Azure/spark-cdm-connector/blob/master/documentation/overview.md#common-read-and-write-options

The samples even shows the correct usage.
https://github.com/Azure/spark-cdm-connector/blob/master/samples/SparkCDMsample.scala
