### ISSUE TITLE
java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/ReadSupport

### ISSUE THREAD

**Issue by BenConstable9** [Azure/spark-cdm-connector#119]
I'm trying to get this connector to work on databricks and I've installed the connector from Maven but running gets this error:

df.write.format("com.microsoft.cdm")
java.lang.NoClassDefFoundError: org/apache/spark/sql/sources/v2/ReadSupport

I realised that I need the correct JAR version for this Spark version but they aren't published on Maven? Is it possible to publish?

**Comment by kecheung** [comment]
[#118](https://github.com/Azure/spark-cdm-connector/issues/118) I suggest you do some basic search and investigation before opening issues. It has been already asked multiple times...
