### ISSUE TITLE
Production?

### ISSUE THREAD

**Issue by SQLArchitect** [Azure/spark-cdm-connector#16]
I'm just curious how long you think it might be before this connector reaches a production worthy status?

I'm strongly advocating in architecture for a client where their core CDM entities are created in their Databricks data pipeline and development may get underway within the next six to eight weeks.

Thank you for your consideration.

Respectfully,

Darryll Petrancuri

**Comment by billgib** [comment]
Hi Darryll, we're still working through a backlog of items to address before we release a public preview of the connector, at which point we'd support its use in production systems.  Tentative goal is mid July.

**Comment by SQLArchitect** [comment]
That is excellent news sir!

Thank you so much.
