### ISSUE TITLE
Support for model.json

### ISSUE THREAD

**Issue by datasharkNL** [Azure/spark-cdm-connector#32]
In the documentation this is written about the model.json:

`Supports writing to CDM folders described by a manifest file only. Write support for model.json file is not planned. `

Please plan the support for model.json. For example the new provided functions for Dynamics 365 (Entity Stores to Data Lake and the coming feature Tables to Data Lake) generate model.json files instead of the other model files.

**Comment by rahuljim** [comment]
does if support get file using model JSON ?
 does it supported in data brick when i uploaded ver 14 in data bricks it crashed

**Comment by rahuljim** [comment]
i am getting error manifest json does not exist any one will help or not

**Comment by bissont** [comment]
Yes, it does support model.json. For example:
 .option("manifest", "/parquet/model.json")

**Comment by datasharkNL** [comment]
> Yes, it does support model.json. For example:
> .option("manifest", "/parquet/model.json")

Does it support writing as model.json? As far as I know it support model.json only as source. But for example Power BI dataflow supports only model.json and not a manifest file

**Comment by rahuljim** [comment]
> Yes, it does support model.json. For example:
> .option("manifest", "/parquet/model.json")
I have used in same way giving error please help

**Comment by bissont** [comment]
Great. closing.

**Comment by jinlinxu** [comment]
It's about writing as model.json, not closed please
