### ISSUE TITLE
Not support reading Contact csv file using model json using data bricks 

### ISSUE THREAD

**Issue by rahuljim** [Azure/spark-cdm-connector#33]
Not support reading Contact csv file using model json using data bricks 
installed ver 14 it got crashed

**Comment by sricheta92** [comment]
Hi @rahuljim. Can you please share the command you executed on databricks? Also, please share the logs. Thank you.

**Comment by rahuljim** [comment]
readDf = ( spark . read . format ( "com.microsoft.cdm" ) . option ( "storage" , storageAccountName ) . option ( "container" , container ) . option ( "entity" , "TestEntity" ) . option ( "appId" , appid ) . option ( "appKey" , appkey ) . option ( "tenantId" , tenantid ) . load ())

It says manifest file not exit 
I have manifest in json format , and contact data in CSV format which in exported from common data model

**Comment by rahuljim** [comment]
[2:33 PM] Singh, Navnit K.
    
containerName = "cdmtest"
storageAccountName = "hdiairetailsdevsecure"
storageAccountKey = "/b7LFEFn7spThw7WYEcxDs1OZyPIm+xDy8cej0KkXFtrNWgkorBy+rZ3rs7LsCQq8cwf2swxKnzhn78+M690Fw=="
spark.conf.set(
  "fs.azure.account.key.%(storageAccountName)s.blob.core.windows.net" % locals(),
  storageAccountKey)
connectionString = "wasbs://%(containerName)s@%(storageAccountName)s.blob.core.windows.net" % locals()
inputLocation = "https://hdiairetailsdevsecure.blob.core.windows.net/cdmtest/model.json"
appID = "----"
tenantID = "--"
appKey = "--"


readDf = (spark.read.format("com.microsoft.cdm").option("storage",storageAccountName).option("container","cdmtest").
          option("manifest", "/cdmtest/Contacts.manifest.cdm.json").option("entity", "contact").option("entityDefinition", "Contact.cdm.json").
          option("appId", appID).option("appKey", appKey).option("tenantId",tenantID ).load())



​[2:34 PM] Singh, Navnit K.
    
Py4JJavaError Traceback (most recent call last) <command-2270770156959806> in <module>----> 1readDf =(spark.read.format("com.microsoft.cdm").option("storage",storageAccountName).option("container","cdmtest").option("entity","contact").option("entityDefinition","Contact.cdm.json").option("manifest","/cdmtest/Contacts.manifest.cdm.json").option("appId", appID).option("appKey", appKey).option("tenantId",tenantID ).load())/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options) 170return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path))) 171else:--> 172return self._df(self._jreader.load()) 173 174@since(1.4)/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args) 1255 answer = self.gateway_client.send_command(command) 1256 return_value = get_return_value( -> 1257 answer, self.gateway_client, self.target_id, self.name)  1258 1259for temp_arg in temp_args:/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw) 61def deco(*a,**kw): 62try:---> 63return f(*a,**kw) 64except py4j.protocol.Py4JJavaError as e: 65 s = e.java_exception.toString()/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name) 326 raise Py4JJavaError(  327"An error occurred while calling {0}{1}{2}.\n".--> 328 format(target_id, ".", name), value)  329else: 330 raise Py4JError( Py4JJavaError: An error occurred while calling o832.load. : java.lang.RuntimeException: Manifest doesn't exist: Contacts.manifest.cdm.json at com.microsoft.cdm.utils.CDMModelCommon.getEntityDec(CDMModelCommon.scala:82) at com.microsoft.cdm.read.CDMDataSourceReader.<init>(CDMDataSourceReader.scala:28) at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:99) at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:19) at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155) at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:290) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:203) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380) at py4j.Gateway.invoke(Gateway.java:295) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.GatewayConnection.run(GatewayConnection.java:251) at java.lang.Thread.run(Thread.java:748)

**Comment by bissont** [comment]
In your second to last comment, the manifest option was not specified. By default it will assume a "default.manifest.cdm.json" if that argument is not provided.

The entityDefinition argument should point to the entity residing in the json file. Depending on your storage structure, this may be the correct argument:
.option("entityDefinition", "Contact.cdm.json/Contact")

Since you didn't specify a "entityDefinitionModelRoot""entityDefinitionContainer", the connector is looking for a file Contact.cdm.json inside of cdmtest.

Do you have a container called cdmtest and then another directory under that with the name cdmtest and manifest file Contacts.manifest.cdm.json under that?

**Comment by rahuljim** [comment]
No we tried it as it was not working 
readDf = (spark.read.format("com.microsoft.cdm").option("storage",storageAccountName).option("container","cdmtest").
option("manifest", "Contacts.manifest.cdm.json").option("entity", "contact").
option("appId", appID).option("appKey", appKey).option("tenantId",tenantID ).load())

we tried this also it did not work

**Comment by rahuljim** [comment]
we tried with multiple option it does not work

**Comment by rahuljim** [comment]
can u send me code with using model json

**Comment by rahuljim** [comment]
readDf = (spark.read.format("com.microsoft.cdm").option("storage",storageAccountName).option("container","cdmtest").option("entity", "contact").option("entityDefinition", "Microsoft.Athena.TrickleFeedService/contact-cdm.json/contact").option("manifest", "model.json").option("appId", appID).option("appKey", appKey).option("tenantId",tenantID ).load())

Py4JJavaError Traceback (most recent call last) <command-2270770156959806> in <module>----> 1readDf =(spark.read.format("com.microsoft.cdm").option("storage",storageAccountName).option("container","cdmtest").option("entity","contact").option("entityDefinition","Microsoft.Athena.TrickleFeedService/contact-cdm.json/contact").option("manifest","model.json").option("appId", appID).option("appKey", appKey).option("tenantId",tenantID ).load())/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options) 170return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path))) 171else:--> 172return self._df(self._jreader.load()) 173 174@since(1.4)/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args) 1255 answer = self.gateway_client.send_command(command) 1256 return_value = get_return_value( -> 1257 answer, self.gateway_client, self.target_id, self.name)  1258 1259for temp_arg in temp_args:/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw) 61def deco(*a,**kw): 62try:---> 63return f(*a,**kw) 64except py4j.protocol.Py4JJavaError as e: 65 s = e.java_exception.toString()/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name) 326 raise Py4JJavaError(  327"An error occurred while calling {0}{1}{2}.\n".--> 328 format(target_id, ".", name), value)  329else: 330 raise Py4JError( Py4JJavaError: An error occurred while calling o2249.load. : java.lang.RuntimeException: Manifest doesn't exist: model.json at com.microsoft.cdm.utils.CDMModelCommon.getEntityDec(CDMModelCommon.scala:82) at com.microsoft.cdm.read.CDMDataSourceReader.<init>(CDMDataSourceReader.scala:28) at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:99) at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:19) at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155) at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:290) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:203) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380) at py4j.Gateway.invoke(Gateway.java:295) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.GatewayConnection.run(GatewayConnection.java:251) at java.lang.Thread.run(Thread.java:748)

**Comment by rahuljim** [comment]
can u please give one example of read and wrtie with CSV file please 
also val df = spark.createDataFrame(spark.sparkContext.parallelize(data), schema) does we need create data frame for read too

**Comment by rahuljim** [comment]
followed not working giving below error 
Py4JJavaError Traceback (most recent call last) in ----> 1readDf =(spark.read.format("com.microsoft.cdm").option("storage",storageAccountName).option("container","cdmtest").option("entity","contact").option("entityDefinition","Microsoft.Athena.TrickleFeedService/contact-cdm.json/contact").option("manifest","model.json").option("appId", appID).option("appKey", appKey).option("tenantId",tenantID ).load())/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options) 170return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path))) 171else:--> 172return self._df(self._jreader.load()) 173 174@since(1.4)/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in call(self, *args) 1255 answer = self.gateway_client.send_command(command) 1256 return_value = get_return_value( -> 1257 answer, self.gateway_client, self.target_id, self.name) 1258 1259for temp_arg in temp_args:/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw) 61def deco(*a,**kw): 62try:---> 63return f(*a,**kw) 64except py4j.protocol.Py4JJavaError as e: 65 s = e.java_exception.toString()/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name) 326 raise Py4JJavaError( 327"An error occurred while calling {0}{1}{2}.\n".--> 328 format(target_id, ".", name), value) 329else: 330 raise Py4JError( Py4JJavaError: An error occurred while calling o2249.load. : java.lang.RuntimeException: Manifest doesn't exist: model.json at com.microsoft.cdm.utils.CDMModelCommon.getEntityDec(CDMModelCommon.scala:82) at com.microsoft.cdm.read.CDMDataSourceReader.(CDMDataSourceReader.scala:28) at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:99) at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:19) at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155) at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:290) at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:203) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) at java.lang.reflect.Method.invoke(Method.java:498) at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244) at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380) at py4j.Gateway.invoke(Gateway.java:295) at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132) at py4j.commands.CallCommand.execute(CallCommand.java:79) at py4j.GatewayConnection.run(GatewayConnection.java:251) at java.lang.Thread.run(Thread.java:748)

**Comment by sricheta92** [comment]
@rahuljim, please enter the relative path of `model.json` from your container in the option `manifest`. Can you try by removing `entityDefinition`? you don't need the option `entityDefinition` when manifest is `model.json`

**Comment by rahuljim** [comment]
i got below error after trying 


----> 7 readdf = (spark.read.format("com.microsoft.cdm").option("storage", "hdiairetailsdevsecure.dfs.core.windows.net").option("container", "cdmtest").option("manifest", "cdm/model.json").option("entity", "contact").option("appId", "").option("appKey", "").option("tenantId", "").load())


/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    170             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    171         else:
--> 172             return self._df(self._jreader.load())
    173 
    174     @since(1.4)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o1095.load.
: java.lang.RuntimeException: Manifest doesn't exist: model.json
	at com.microsoft.cdm.utils.CDMModelCommon.getEntityDec(CDMModelCommon.scala:82)
	at com.microsoft.cdm.read.CDMDataSourceReader.<init>(CDMDataSourceReader.scala:28)
	at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:99)
	at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:19)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:290)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

**Comment by bissont** [comment]
As the error message you posted shows, a model.json does not exist:
> Py4JJavaError: An error occurred while calling o1095.load.
> : java.lang.RuntimeException: Manifest doesn't exist: model.json

**Comment by rahuljim** [comment]
Yes it exit but also showing this issue we are facing

**Comment by bissont** [comment]
Can you share the directory listing of:
* /cdmtest
* /cdmtest/cdm

**Comment by rahuljim** [comment]
![image](https://user-images.githubusercontent.com/58183111/85251159-349bfc80-b476-11ea-9795-9bf477161596.png)

this is our directory and we are getting below error :
spark.read.format("com.microsoft.cdm") .option("storage", "hdiairetailsdevsecure.dfs.core.windows.net") .option("container", "cdmtest") .option("manifest", "/model.json") .option("entity", "contact") .option("appId",-ba011e") .option("appKey", "7Q3") .option("tenantId", "3503d") .load()

/databricks/spark/python/pyspark/sql/readwriter.py in load(self, path, format, schema, **options)
    170             return self._df(self._jreader.load(self._spark._sc._jvm.PythonUtils.toSeq(path)))
    171         else:
--> 172             return self._df(self._jreader.load())
    173 
    174     @since(1.4)

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py in __call__(self, *args)
   1255         answer = self.gateway_client.send_command(command)
   1256         return_value = get_return_value(
-> 1257             answer, self.gateway_client, self.target_id, self.name)
   1258 
   1259         for temp_arg in temp_args:

/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     61     def deco(*a, **kw):
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:
     65             s = e.java_exception.toString()

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    326                 raise Py4JJavaError(
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:
    330                 raise Py4JError(

Py4JJavaError: An error occurred while calling o498.load.
: java.lang.RuntimeException: Manifest doesn't exist: model.json
	at com.microsoft.cdm.utils.CDMModelCommon.getEntityDec(CDMModelCommon.scala:82)
	at com.microsoft.cdm.read.CDMDataSourceReader.<init>(CDMDataSourceReader.scala:28)
	at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:99)
	at com.microsoft.cdm.DefaultSource.createReader(DefaultSource.scala:19)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$SourceHelpers.createReader(DataSourceV2Relation.scala:155)
	at org.apache.spark.sql.execution.datasources.v2.DataSourceV2Relation$.create(DataSourceV2Relation.scala:172)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:290)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:203)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)

**Comment by sricheta92** [comment]
Can you open model.json and verify if it has an entity name "contact" ?

**Comment by rahuljim** [comment]
Yes it has entity name contact

**Comment by rahuljim** [comment]
![image](https://user-images.githubusercontent.com/58183111/85264854-f5c67080-b48e-11ea-8d6e-ad7e780d01f4.png)

**Comment by rahuljim** [comment]
please suggest anything else need to be checked

**Comment by rahuljim** [comment]
Can u please answer here any resolution

**Comment by sricheta92** [comment]
Can you please share your model.json and contact folder to asksparkcdm@microsoft.com.

**Comment by rahuljim** [comment]
Sure will mail

**Comment by rahuljim** [comment]
Hi All,

As discussed over git hub with sricheta92 sharing the  model. Son and contact folder .

Requesting to please help on priority .

spark.read.format("com.microsoft.cdm") .option("storage", ".dfs.core.windows.net") .option("container", "") .option("manifest", "/model.json") .option("entity", "contact") .option("appId",-ba011e") .option("appKey", "7Q3") .option("tenantId", "3503d") .load()

Regards,
Rahul Jain

**Comment by sricheta92** [comment]
Hello @rahuljim, 
you must have got an email address from us regarding this issue few weeks ago.. Can you please update us whether your issue has been resolved or not?

**Comment by srichetar** [comment]
Closing this. Please raise a new issue if you still face errors with 0.18.1
