### ISSUE TITLE
No number of partition option while writing with the connector

### ISSUE THREAD

**Issue by Sandy247** [Azure/spark-cdm-connector#40]
There does not seem to be a option to specify the number of partitions while writing with the connector. Is this not supported yet or am I missing something?

**Comment by bissont** [comment]
Hi,

You can control the number of partitions with something like:

val df= spark.createDataFrame(spark.sparkContext.parallelize(data, 2), schema)

to have 2 partitions written out.

Tim

**Comment by Sandy247** [comment]
Thanks @bissont!
