### ISSUE TITLE
Reading and rewriting data written with the connector fails with schema mismatch error for data with decimal types

### ISSUE THREAD

**Issue by Sandy247** [Azure/spark-cdm-connector#42]
The error can be reproduced by reading and rewriting the data(different or same location) in the implicit write case in [SparkCDMsamplesPython](https://github.com/Azure/spark-cdm-connector/blob/master/samples/SparkCDMsamplePython.ipynb )... The error thrown is

"**dataframe schema does not match the cdm schema for  (decimal column name)**"

Removing or casting the decimal fields works fine but aren't ideal. It would be great if someone could take a look at this and let me know if this is a known issue or if I am missing something.

**Comment by sricheta92** [comment]
@Sandy247  In which version of connector did you face this issue?

**Comment by Sandy247** [comment]
Hey @sricheta92, I faced this with version 0.16.

**Comment by sricheta92** [comment]
Can you use 0.17 version of the connector? This issue was fixed in 0.17.

**Comment by Sandy247** [comment]
Thanks @sricheta92... Seems to be working fine with the sample notebook. Will test with our use case and get back to you. Also, do you guys have any working timeline for spark 3.0 support with this connector?

**Comment by srichetar** [comment]
Closing this as this issue has been fixed in 0.17. We don't have an estimate for spark 3.0 support yet.

**Comment by sultanmkhan** [comment]
I am using Azure Synapse Analytics(Spark Pool). How can I check and update the connector version?
