### ISSUE TITLE
Previously working read/write cases failing

### ISSUE THREAD

**Issue by Sandy247** [Azure/spark-cdm-connector#47]
I have a few ingested manifest files that were previously being read and overwritten without any hiccups. Today, all of a sudden, I have started facing issues with reading and writing them(some pipelines started failing).
The reads fail with:
**Py4JJavaError: An error occurred while calling o1622.load.
: java.util.concurrent.ExecutionException: java.lang.NullPointerException**
whereas, the writes fail with:
**Py4JJavaError: An error occurred while calling o2978.save.
: java.util.concurrent.ExecutionException: java.lang.Exception: CdmE2ERelationship | Integrity check failed. Reason: The object 'SparkManifestLocation:/RuleStitchMatchPairs.manifest.cdm.json//relationships/null' is missing the following required fields: 'fromEntity', 'fromEntityAttribute', 'toEntity', 'toEntityAttribute'**

What is weird is that these exact files/cases had been working for the past 2-3 weeks up until last Friday. A few of the files work while the others don't and there are no patterns among the failures. It would be great anyone could help me debug these issues as a few production pipelines are running on the connector(given how stable it was). Thanks in advance.

**Comment by asksparkcdm** [comment]
Hello Sayandip,

This appears to be an issue with CDM SDK. Can you share the following information to help us debug the issue -


  1.  Please share the entire log of read/write failure.
  2.  Please specify on which version were the read/write flows working ? and on which version did you see these errors?
  3.  Specify the exact command you executed? If possible, also share the necessary CDM folder/data to reproduce this issue on our issue

You can share all these information on asksparkcdm@microsoft.com

Thanks,
Sricheta.

**Comment by billgib** [comment]
This issue was closed after confirmation that the issue was caused by a data corruption, not a problem with the Spark CDM Connector
