### ISSUE TITLE
Error When Using Custom Delimiter in Python

### ISSUE THREAD

**Issue by InitionsJulius** [Azure/spark-cdm-connector#54]
Using a custom delimiter with the CDM write function always returns the error: **"Only one character is allowed in delimiter"**.
The function works if the option "delimiter" is omitted. Then the default (comma) is used in the output CSV file.

**Function**
(outDf.write.format("com.microsoft.cdm")
  .option("storage", storageAccountName)
  .option("container", container)
  .option("manifest", "/Databricks/default.manifest.cdm.json")
  .option("manifestPath", container + "/Databricks/default.manifest.cdm.json")
  .option("format", "csv")
  .option("columnHeaders", "false")
  **.option("delimiter", ";")** 
  .option("entity", "Sales")
  .option("appId", appid)
  .option("appKey", appkey)
  .option("tenantId", tenantid)
  .mode("overwrite") # or "append"
  .save())

**Error Message:**
java.lang.IllegalArgumentException: Invalid Delimiter - ,. Only one character is allowed in delimiter. Input should be a character.

Py4JJavaError                             Traceback (most recent call last)
/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling o1092.save.
: java.lang.IllegalArgumentException: Invalid Delimiter - ,. Only one character is allowed in delimiter. Input should be a character.
	at com.microsoft.cdm.DefaultSource.getDelimiterChar(DefaultSource.scala:138)
	at com.microsoft.cdm.DefaultSource.createWriter(DefaultSource.scala:284)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:278)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

**Comment by asksparkcdm** [comment]
Hi,

Can you please try to use it like –

.option("delimiter", ‘;’)

Pass the delimiter inside a single quote.

Thanks,
Sricheta.

**Comment by InitionsJulius** [comment]
Hi Sricheta,
I had tried passing the parameter in single quotes as well (i.e. ','). It also didn't work.
Kind regards,
Julius

**Comment by asksparkcdm** [comment]
df.write.format("com.microsoft.cdm")
  .option("storage", storageAccountName)
  .option("manifestPath",   "output/csvHeader/default.manifest.cdm.json")
  .option("entity", "CSVHeaderTest")
  .option("format", "csv")
  .option("delimiter", ';')
  .option("columnHeaders", false)
  .option("appId", appId)
  .option("appKey", appKey)
  .option("tenantId", tenantID)
  .mode(SaveMode.Overwrite)
  .save()

This works for me. Please check if you are passing the delimiter correctly as shown above.

**Comment by InitionsJulius** [comment]
1) I tested the delimiter again (with single and with double parentheses). It still doesn't work with the same error.

2) Note:
These two options did not work for me:
 .option("columnHeaders", false)
 .mode(SaveMode.Overwrite)

I had to change them to:
 .option("columnHeaders", "false")
 .mode("overwrite")

3) If I omit the delimiter option, then I get an comma delimited CSV file.

4) I added the jar file as a library to databricks
![image](https://user-images.githubusercontent.com/54058546/97154129-d5c3f800-1773-11eb-8ec5-0e4d26f56d15.png)

5) The databricks runtime version is: 6.6 (includes Apache Spark 2.4.5, Scala 2.11)

**Comment by InitionsJulius** [comment]
The same problem also occurs when using the read function, e.g.:

readDf = (spark.read.format("com.microsoft.cdm")
  .option("storage", storageAccountName)
  .option("container", container)
  .option("manifestPath", container + "/somePath/default.manifest.cdm.json")
  .option("entity", "Sales")
  **.option("delimiter", ';') # Only works if CSV file is comma delimited and this option is omitted.**
  .option("appId", appid)
  .option("appKey", appkey)
  .option("tenantId", tenantid)
  .load())

**Comment by asksparkcdm** [comment]
Hi,


  1.  Delimiter and columnHeader option are not required on “read” operation because during read, the connector reads the value from manifest file.



    "arguments" : [

                {

                 "name" : "delimiter",

                  "value" : ","

                },

                {

                  "name" : "columnHeaders",

                  "value" : "true"

                }

              ]


  1.  Please email – asksparkcdm@microsoft.cdm<mailto:asksparkcdm@microsoft.cdm> with the issue on write.



Thanks,
Sricheta.

**Comment by srichetar** [comment]
This is fixed in 0.18.2 version of the connector. Can you please verify and close it?
