### ISSUE TITLE
Overriding from configPath - sample problem

### ISSUE THREAD

**Issue by kcris** [Azure/spark-cdm-connector#62]
Hi,
I tried to execute sample [5] (`Overriding from configPath`) available here:
https://github.com/Azure/spark-cdm-connector/blob/master/samples/SparkCDMsamplePython.ipynb

these lines have some issues
```
  .option("entityDefinitionModelRoot", "Models")   # fetches config.json from this location and finds definition of "core" alias, if configPath option is not present
  .option("configPath" "/config")  # Add your config.json to override the above definition
  .option("entityDefinitionStorage", "<storage1>.dfs.core.windows.net") // entityDefinitionModelRoot contains in this storage account
```
1. based on previous examples I think `.option("entityDefinitionModelRoot", "Models")` should really be `.option("entityDefinitionModelRoot", container+"Models")`

2. there is a missing comma here `.option("configPath" "/config") `

3. python comment should start with `#` here: `// entityDefinitionModelRoot contains in this storage account`

All these are minor issues. Once fixed, the main problem was that:

4. I was not able to find `Config.json` inside `/config`.
It is not clear if `/config` is relative to `entityDefinitionModelRoot`, but if that's the case, the `Config.json` was present when I tested and yet it was not found. So I was unable to run this sample. I tried both `Config.json` (according to error messages) and `config.json` (according to provided sample)

Please take a look

**Comment by srichetar** [comment]
Hi, Thanks for letting us know about minor typos in the python sample notebook. There is a config.json in https://github.com/Azure/spark-cdm-connector/tree/master/samples/Contacts. 
Please read - https://github.com/Azure/spark-cdm-connector/blob/master/documentation/overview.md#explicit-write-options. `configPath` is should be an absolute location location.  eg: - `/<conatinername>/<foldername_ where_config.json_resides>`

**Comment by kcris** [comment]
Thanks!
I think I have  one more problem though: there is a missing dependency: `CustomerCategory.cdm.json` schema is not part of the `samples/Contacts` folder

**Comment by bissont** [comment]
Can you try again. I'm not sure how we missed that.

**Comment by kcris** [comment]
Thanks!

my next issue is that TrackedEntity (defined in _salesimports.cdm.json as `core:/TrackedEntity.cdm.json`) is not found
I do have the file available, since I copied the whole contents of `samples/Contacts` to my datalake container

see below
![image](https://user-images.githubusercontent.com/812733/101809459-de03a700-3b17-11eb-929e-6816d0206cf6.png)

**Comment by srichetar** [comment]
You need to change the location as per your needs, the location where TrackedEntity is places. 
```
"config" : {
        "hostname" : "srichetastorage.dfs.core.windows.net",
        "root" : "/outputsubmanifest/example-public-standards",
        "tenant" : "72f988bf-86f1-41af-91ab-2d7cd011db47",
        "clientId" : "6c3f525f-bdcb-4677-bed6-24f0b43add13",
        "timeout" : 5000,
        "maximumTimeout" : 20000,
        "numberOfRetries" : 2
      },
```

The TrackedEntity.cdm.json inturn has 
```
    "imports": [
        {
            "corpusPath": "cdm:/foundations.cdm.json"
        }
    ],
```
You need the CDM foundation files to get this working. The sample file just tells you how to use the options.

**Comment by kcris** [comment]
got it, thanks a lot
