### ISSUE TITLE
Error in - Explicit write, creating an entity in a CDM folder based on a pre-defined model

### ISSUE THREAD

**Issue by sathya1972** [Azure/spark-cdm-connector#71]
# UPLOAD CDM FILES FIRST
# To run this example, first create a /Models/Contacts folder to your demo container in ADLS gen2,
# then upload the provided Contacts.manifest.cdm.json, Person.cdm.json, Entity.cdm.json files

When I was trying to execute following code segment, I get - Entity definition model file &#34;/Contacts/Person.cdm.json&#34; not found., All the directories and files are in place as per above comments.

My directory structure is - adbdemofilesystem / Models / Contacts
Files under  Contacts are -  Contacts.manifest.cdm.json, Person.cdm.json, Entity.cdm.json files

# Create the dataframe that matches the CDM definition of the entity, Person
df2 = spark.createDataFrame(spark.sparkContext.parallelize(data2, 1), schema2)
(df2.write.format("com.microsoft.cdm")
  .option("storage", storageAccountName)
  .option("manifestPath", container + "/Data/Contacts/root.manifest.cdm.json")
  .option("entity", "Person")
  .option("entityDefinitionModelRoot", container + "/Models") 
  .option("entityDefinitionPath", "/Contacts/Person.cdm.json/Person")
  .mode("overwrite")
  .save())
-----

-----------------------------------------------------------------------
Py4JJavaError                             Traceback (most recent call last)
/databricks/spark/python/pyspark/sql/utils.py in deco(*a, **kw)
     62         try:
---> 63             return f(*a, **kw)
     64         except py4j.protocol.Py4JJavaError as e:

/databricks/spark/python/lib/py4j-0.10.7-src.zip/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling o1112.save.
: java.lang.IllegalArgumentException: Entity definition model file "/Contacts/Person.cdm.json" not found
	at com.microsoft.cdm.utils.CDMModelCommon.<init>(CDMModelCommon.scala:85)
	at com.microsoft.cdm.utils.CDMModelWriter.<init>(CDMModelWriter.scala:38)
	at com.microsoft.cdm.write.CDMDataSourceWriter.<init>(CDMDataSourceWriter.scala:69)
	at com.microsoft.cdm.DefaultSource.createWriter(DefaultSource.scala:295)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:277)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)

During handling of the above exception, another exception occurred:

IllegalArgumentException                  Traceback (most recent call last)
<command-1725492405067567> in <module>
     34   .option("entityDefinitionModelRoot", container + "/Models")
     35   .option("entityDefinitionPath", "/Contacts/Person.cdm.json/Person")
---> 36   .mode("overwrite")
     37   .save())

**Comment by bissont** [comment]
Were you able to run the previous two cells (implicit and explicit write from pre-defined model)  from the example?

I just re-ran the sample and it should still work:
![image](https://user-images.githubusercontent.com/509759/111247558-73a24d00-85c5-11eb-93c6-d4b2dcba4e6d.png)

Can you share a similar snapshot?

**Comment by sathya1972** [comment]
Yes I was able to successfully run. 


Sent from Yahoo Mail for iPhone


On Monday, March 15, 2021, 7:37 PM, bissont ***@***.***> wrote:




Were you able to run the previous two cells (implicit and explicit write from pre-defined model) from the example?

I just re-ran the sample and it should still work:


Can you share a similar snapshot?

**Comment by bissont** [comment]
That looks similar to what I have. 

Can you also take a snapshot of the contents at the container level? Is there a directory called ImplicitTest at the same level Models?

**Comment by sathya1972** [comment]
Thank you for the quick response. Yes. I do have directory called ImplicitTest at the same level Models.

![image](https://user-images.githubusercontent.com/15679756/111360615-316f1f00-864a-11eb-80a3-1f633de55f35.png)

**Comment by bissont** [comment]
I'm not sure what the error is then. Can you reach out to asksparkcdm@microsoft.com and we can schedule some time to debug it.

**Comment by sathya1972** [comment]
Thank you for your  quick response.

Hello, Aksparkcdm team,
Can you please take a look at this issue and help me on this? I am happy to schedule a working session to resolve this. Appreciate your help.

    On Tuesday, 16 March, 2021, 11:36:43 am GMT-7, bissont ***@***.***> wrote:  
 
 


I'm not sure what the error is then. Can you reach out to ***@***.*** and we can schedule some time to debug it.

**Comment by bissont** [comment]
Hi, What is your e-mail?

**Comment by sathya1972** [comment]
My email ids -1 ***@***.*** ***@***.***

Thanks 
Sent from Yahoo Mail for iPhone


On Tuesday, March 16, 2021, 1:10 PM, bissont ***@***.***> wrote:



Hi, What is your e-mail?

**Comment by sathya1972** [comment]
I sent an invite for this evening.

Tim

From: samhitha sathya ***@***.***>
Sent: Tuesday, March 16, 2021 12:47 PM
To: Azure/spark-cdm-connector ***@***.***>; Azure/spark-cdm-connector ***@***.***>; Ask Spark CDM ***@***.***>
Cc: Author ***@***.***>; ***@***.***
Subject: [EXTERNAL] Re: [Azure/spark-cdm-connector] Error in - Explicit write, creating an entity in a CDM folder based on a pre-defined model (#71)

Thank you for your  quick response.


Hello, Aksparkcdm team,

Can you please take a look at this issue and help me on this? I am happy to schedule a working session to resolve this. Appreciate your help.


On Tuesday, 16 March, 2021, 11:36:43 am GMT-7, bissont ***@***.******@***.***>> wrote:



I'm not sure what the error is then. Can you reach out to ***@***.******@***.***> and we can schedule some time to debug it.

-

**Comment by sathya1972** [comment]
Tim, Thank you for the quick response. I just see below email. I do not see meeting invite.  Am I missing anything?
Thanks.
    On Tuesday, 16 March, 2021, 01:25:32 pm GMT-7, Timothy Bisson ***@***.***> wrote:  
 
 
I sent an invite for this evening.
 
  
 
Tim
 
  
 
From: samhitha sathya ***@***.***> 
Sent: Tuesday, March 16, 2021 12:47 PM
To: Azure/spark-cdm-connector ***@***.***>; Azure/spark-cdm-connector ***@***.***>; Ask Spark CDM ***@***.***>
Cc: Author ***@***.***>; ***@***.***
Subject: [EXTERNAL] Re: [Azure/spark-cdm-connector] Error in - Explicit write, creating an entity in a CDM folder based on a pre-defined model (#71)
 
  
 
Thank you for your  quick response.
 
  
 
  
 
Hello, Aksparkcdm team,
 
  
 
Can you please take a look at this issue and help me on this? I am happy to schedule a working session to resolve this. Appreciate your help.
 
  
 
  
 
On Tuesday, 16 March, 2021, 11:36:43 am GMT-7, bissont ***@***.***> wrote:
 
  
 
  
 
I'm not sure what the error is then. Can you reach out ***@***.*** and we can schedule some time to debug it.

**Comment by sathya1972** [comment]
thank you for your help. I am closing this issue.
