### ISSUE TITLE
The specified resource name contains invalid characters

### ISSUE THREAD

**Issue by GDR88** [Azure/spark-cdm-connector#79]
Hi,

I'm trying to query D365 F&O files using this connector. I think I did everything right, however, i'm getting the following error that I can't seem to solve. Any suggestions? 
The actual files are in the GeneralJournalAccountEntry folder but I would think the manifest structure knows that. 

Please let me know if you need further information!

Thanks!

![image](https://user-images.githubusercontent.com/86482458/123442390-20349780-d5d5-11eb-9373-0e9ce673df8e.png)
![image](https://user-images.githubusercontent.com/86482458/123442696-6ee23180-d5d5-11eb-92a3-dba4098631b2.png)

**Comment by srichetar** [comment]
Looks you are using an invalid name for containers https://docs.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata

**Comment by GDR88** [comment]
storage needed to be dfs as stated in the readme. Sorry!
