### ISSUE TITLE
Schema drift

### ISSUE THREAD

**Issue by rgk85** [Azure/spark-cdm-connector#86]
I have encountered an issue where the schema includes more columns than my actual data, the reading throws an error also saying this.
![image](https://user-images.githubusercontent.com/40987871/144590652-a852acef-37b3-43e9-849d-72207f43aa80.png)

![image](https://user-images.githubusercontent.com/40987871/144591087-6a373603-7f45-42f5-8cec-e7f734ca8230.png)

I was reading the documentation and unsupported scenarios and as far as I understood on the scenario where the actual data has more columns than specified in the schema is not supported, am I missing something in the documentation or perhaps I'm doing something wrong, perhaps a workaround is in place?

spark-cdm-connector 0.19.1
Databricks 6.4
Spark 2.4.5

**Comment by Nuglar** [comment]
This may be relatede to the issue we were facing, discussed in a previous issue:
https://github.com/Azure/spark-cdm-connector/issues/84

Things to try:
- using the permissive mode option
  `.option("mode", "permissive")`
- resyncing from dataverse side
