### ISSUE TITLE
Version Incompatibility issue with spark-cdm-connector

### ISSUE THREAD

**Issue by pavanreddy88** [Azure/spark-cdm-connector#92]
Hi @asksparkcdm@microsoft.com
I am from Linkedin, we are having compatibility issue with spark-cdm-connector, to give a little context I have a cdm data in ADLS which I’m trying to read into Databricks 9.1 LTS Apache Spark 3.1.2, Scala 2.12, I have installed com.microsoft.azure:spark-cdm-connector:0.19.1 and org.neo4j:neo4j-connector-apache-spark_2.12:4.1.2_for_spark_3, I tried multiple versions of neo4j-connector and spark-cdm-connector as well and its throwing this error
ERROR: java.lang.NoClassDefFoundError:org/apache/spark/sql/sources/v2/ReadSupport.
 
Can you please provide proper version of spark-cdm-connector and neo4j-connector compatible for Databricks 9.1 LTS Apache Spark 3.1.2, Scala 2.12  from these below available versions?
spark-cdm-connector versions available in Databricks
![CDM-connector](https://user-images.githubusercontent.com/18541576/168181115-1a67e3c9-f931-4558-92bf-2ecf301e2dee.png)

neo4j-connector available in Databricks
![Neo4j](https://user-images.githubusercontent.com/18541576/168181130-219f412b-f74c-4eb9-b46f-2aa5334894fb.png)

Description automatically generated
 
ERROR context.
![Screen Shot 2022-05-12 at 4 23 41 PM](https://user-images.githubusercontent.com/18541576/168181178-ca15f2a9-94e2-4aeb-93a4-54476f6c3c91.png)

Description automatically generated
 
Pavan

**Comment by bit007** [comment]
I am also facing similar issue while using 10.4 LTS (includes Apache Spark 3.2.1, Scala 2.12)

**Comment by kcheeeung** [comment]
The jar version 0.19.1 is for Spark 2.4 and you are using Spark 3, therefore giving class not found exception.

**Comment by kecheung** [comment]
Added to pinned issues https://github.com/Azure/spark-cdm-connector/issues/118
