### ISSUE TITLE
spark-cdm-connector NOT WORKING WITH SPARK 3.0

### ISSUE THREAD

**Issue by prpawar1** [Azure/spark-cdm-connector#96]
Hi, I have been trying to use spark-cdm-connector to read/write cdm files from/to ADLS using Databricks. But I am getting support error for the same when I use a cluster with Spark 3.0 configuration but working perfectly well with Spark 2.0, whereas its mentioned in the official document that its supported by both Spark 2.0 and 3.0.

Could you please help me with this ?

**Comment by kcheeeung** [comment]
See #92.
